==1352== Memcheck, a memory error detector
==1352== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==1352== Using Valgrind-3.12.0.SVN and LibVEX; rerun with -h for copyright info
==1352== Command: ./bin/utest
==1352== 
==1352== Syscall param socketcall.recvfrom(buf) points to unaddressable byte(s)
==1352==    at 0x4E484BD: recv (recv.c:28)
==1352==    by 0x2F883C: ndsl::net::TcpConnection::onRecv(char*, long*, int, void (*)(void*), void*) (TcpConnection.cc:161)
==1352==    by 0x2F45F4: ____C_A_T_C_H____T_E_S_T____0() (TcpConnectionTest.cc:100)
==1352==    by 0x26B0B5: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1352==    by 0x26A818: Catch::TestCase::invoke() const (catch.hpp:10232)
==1352==    by 0x2658F0: Catch::RunContext::invokeActiveTestCase() (catch.hpp:9104)
==1352==    by 0x26564A: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:9078)
==1352==    by 0x26434C: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:8861)
==1352==    by 0x266C12: Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) (catch.hpp:9394)
==1352==    by 0x267E59: Catch::Session::runInternal() (catch.hpp:9592)
==1352==    by 0x267C2E: Catch::Session::run() (catch.hpp:9549)
==1352==    by 0x267BCE: Catch::Session::run(int, char**) (catch.hpp:9517)
==1352==  Address 0xfff001000 is not stack'd, malloc'd or (recently) free'd
==1352== 
===============================================================================
All tests passed (11 assertions in 1 test case)

==1352== 
==1352== HEAP SUMMARY:
==1352==     in use at exit: 1,820 bytes in 12 blocks
==1352==   total heap usage: 1,799 allocs, 1,787 frees, 329,828 bytes allocated
==1352== 
==1352== 12 bytes in 1 blocks are definitely lost in loss record 1 of 12
==1352==    at 0x4C2BBAF: malloc (vg_replace_malloc.c:299)
==1352==    by 0x2F4569: ____C_A_T_C_H____T_E_S_T____0() (TcpConnectionTest.cc:91)
==1352==    by 0x26B0B5: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1352==    by 0x26A818: Catch::TestCase::invoke() const (catch.hpp:10232)
==1352==    by 0x2658F0: Catch::RunContext::invokeActiveTestCase() (catch.hpp:9104)
==1352==    by 0x26564A: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:9078)
==1352==    by 0x26434C: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:8861)
==1352==    by 0x266C12: Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) (catch.hpp:9394)
==1352==    by 0x267E59: Catch::Session::runInternal() (catch.hpp:9592)
==1352==    by 0x267C2E: Catch::Session::run() (catch.hpp:9549)
==1352==    by 0x267BCE: Catch::Session::run(int, char**) (catch.hpp:9517)
==1352==    by 0x27AF84: main (test.cc:16)
==1352== 
==1352== 64 bytes in 1 blocks are indirectly lost in loss record 2 of 12
==1352==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==1352==    by 0x2F9D77: __gnu_cxx::new_allocator<ndsl::net::TcpConnection::SInfo**>::allocate(unsigned long, void const*) (new_allocator.h:104)
==1352==    by 0x2F997A: std::allocator_traits<std::allocator<ndsl::net::TcpConnection::SInfo**> >::allocate(std::allocator<ndsl::net::TcpConnection::SInfo**>&, unsigned long) (alloc_traits.h:436)
==1352==    by 0x2F967A: std::_Deque_base<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::_M_allocate_map(unsigned long) (stl_deque.h:614)
==1352==    by 0x2F9218: std::_Deque_base<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::_M_initialize_map(unsigned long) (stl_deque.h:687)
==1352==    by 0x2F8E98: std::_Deque_base<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::_Deque_base() (stl_deque.h:490)
==1352==    by 0x2F8D2B: std::deque<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::deque() (stl_deque.h:884)
==1352==    by 0x2F82DD: ndsl::net::TcpConnection::TcpConnection() (TcpConnection.cc:28)
==1352==    by 0x2F411D: ____C_A_T_C_H____T_E_S_T____0() (TcpConnectionTest.cc:70)
==1352==    by 0x26B0B5: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1352==    by 0x26A818: Catch::TestCase::invoke() const (catch.hpp:10232)
==1352==    by 0x2658F0: Catch::RunContext::invokeActiveTestCase() (catch.hpp:9104)
==1352== 
==1352== 64 bytes in 1 blocks are indirectly lost in loss record 3 of 12
==1352==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==1352==    by 0x2F9D77: __gnu_cxx::new_allocator<ndsl::net::TcpConnection::SInfo**>::allocate(unsigned long, void const*) (new_allocator.h:104)
==1352==    by 0x2F997A: std::allocator_traits<std::allocator<ndsl::net::TcpConnection::SInfo**> >::allocate(std::allocator<ndsl::net::TcpConnection::SInfo**>&, unsigned long) (alloc_traits.h:436)
==1352==    by 0x2F967A: std::_Deque_base<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::_M_allocate_map(unsigned long) (stl_deque.h:614)
==1352==    by 0x2F9218: std::_Deque_base<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::_M_initialize_map(unsigned long) (stl_deque.h:687)
==1352==    by 0x2F8E98: std::_Deque_base<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::_Deque_base() (stl_deque.h:490)
==1352==    by 0x2F8D2B: std::deque<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::deque() (stl_deque.h:884)
==1352==    by 0x2F82DD: ndsl::net::TcpConnection::TcpConnection() (TcpConnection.cc:28)
==1352==    by 0x2FB0CF: ndsl::net::TcpClient::onConnect(ndsl::net::EventLoop*, bool, ndsl::net::SocketAddress4*) (TcpClient.cc:52)
==1352==    by 0x2F4246: ____C_A_T_C_H____T_E_S_T____0() (TcpConnectionTest.cc:78)
==1352==    by 0x26B0B5: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1352==    by 0x26A818: Catch::TestCase::invoke() const (catch.hpp:10232)
==1352== 
==1352== 72 bytes in 1 blocks are indirectly lost in loss record 4 of 12
==1352==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==1352==    by 0x2F7EF0: ndsl::net::TcpAcceptor::start(ndsl::net::SocketAddress4) (TcpAcceptor.cc:79)
==1352==    by 0x2F40E5: ____C_A_T_C_H____T_E_S_T____0() (TcpConnectionTest.cc:61)
==1352==    by 0x26B0B5: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1352==    by 0x26A818: Catch::TestCase::invoke() const (catch.hpp:10232)
==1352==    by 0x2658F0: Catch::RunContext::invokeActiveTestCase() (catch.hpp:9104)
==1352==    by 0x26564A: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:9078)
==1352==    by 0x26434C: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:8861)
==1352==    by 0x266C12: Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) (catch.hpp:9394)
==1352==    by 0x267E59: Catch::Session::runInternal() (catch.hpp:9592)
==1352==    by 0x267C2E: Catch::Session::run() (catch.hpp:9549)
==1352==    by 0x267BCE: Catch::Session::run(int, char**) (catch.hpp:9517)
==1352== 
==1352== 72 bytes in 1 blocks are indirectly lost in loss record 5 of 12
==1352==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==1352==    by 0x2F83AB: ndsl::net::TcpConnection::createChannel(int, ndsl::net::EventLoop*) (TcpConnection.cc:35)
==1352==    by 0x2FB135: ndsl::net::TcpClient::onConnect(ndsl::net::EventLoop*, bool, ndsl::net::SocketAddress4*) (TcpClient.cc:58)
==1352==    by 0x2F4246: ____C_A_T_C_H____T_E_S_T____0() (TcpConnectionTest.cc:78)
==1352==    by 0x26B0B5: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1352==    by 0x26A818: Catch::TestCase::invoke() const (catch.hpp:10232)
==1352==    by 0x2658F0: Catch::RunContext::invokeActiveTestCase() (catch.hpp:9104)
==1352==    by 0x26564A: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:9078)
==1352==    by 0x26434C: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:8861)
==1352==    by 0x266C12: Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) (catch.hpp:9394)
==1352==    by 0x267E59: Catch::Session::runInternal() (catch.hpp:9592)
==1352==    by 0x267C2E: Catch::Session::run() (catch.hpp:9549)
==1352== 
==1352== 72 bytes in 1 blocks are indirectly lost in loss record 6 of 12
==1352==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==1352==    by 0x2F83AB: ndsl::net::TcpConnection::createChannel(int, ndsl::net::EventLoop*) (TcpConnection.cc:35)
==1352==    by 0x2F81F2: ndsl::net::TcpAcceptor::handleRead(void*) (TcpAcceptor.cc:156)
==1352==    by 0x2FBA28: ndsl::net::BaseChannel::handleEvent() (BaseChannel.cc:41)
==1352==    by 0x2F69BD: ndsl::net::EventLoop::loop(void*) (EventLoop.cc:109)
==1352==    by 0x2F4398: ____C_A_T_C_H____T_E_S_T____0() (TcpConnectionTest.cc:84)
==1352==    by 0x26B0B5: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1352==    by 0x26A818: Catch::TestCase::invoke() const (catch.hpp:10232)
==1352==    by 0x2658F0: Catch::RunContext::invokeActiveTestCase() (catch.hpp:9104)
==1352==    by 0x26564A: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:9078)
==1352==    by 0x26434C: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:8861)
==1352==    by 0x266C12: Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) (catch.hpp:9394)
==1352== 
==1352== 168 bytes in 1 blocks are indirectly lost in loss record 7 of 12
==1352==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==1352==    by 0x2F4112: ____C_A_T_C_H____T_E_S_T____0() (TcpConnectionTest.cc:70)
==1352==    by 0x26B0B5: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1352==    by 0x26A818: Catch::TestCase::invoke() const (catch.hpp:10232)
==1352==    by 0x2658F0: Catch::RunContext::invokeActiveTestCase() (catch.hpp:9104)
==1352==    by 0x26564A: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:9078)
==1352==    by 0x26434C: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:8861)
==1352==    by 0x266C12: Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) (catch.hpp:9394)
==1352==    by 0x267E59: Catch::Session::runInternal() (catch.hpp:9592)
==1352==    by 0x267C2E: Catch::Session::run() (catch.hpp:9549)
==1352==    by 0x267BCE: Catch::Session::run(int, char**) (catch.hpp:9517)
==1352==    by 0x27AF84: main (test.cc:16)
==1352== 
==1352== 168 bytes in 1 blocks are indirectly lost in loss record 8 of 12
==1352==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==1352==    by 0x2FB0C4: ndsl::net::TcpClient::onConnect(ndsl::net::EventLoop*, bool, ndsl::net::SocketAddress4*) (TcpClient.cc:52)
==1352==    by 0x2F4246: ____C_A_T_C_H____T_E_S_T____0() (TcpConnectionTest.cc:78)
==1352==    by 0x26B0B5: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1352==    by 0x26A818: Catch::TestCase::invoke() const (catch.hpp:10232)
==1352==    by 0x2658F0: Catch::RunContext::invokeActiveTestCase() (catch.hpp:9104)
==1352==    by 0x26564A: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:9078)
==1352==    by 0x26434C: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:8861)
==1352==    by 0x266C12: Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) (catch.hpp:9394)
==1352==    by 0x267E59: Catch::Session::runInternal() (catch.hpp:9592)
==1352==    by 0x267C2E: Catch::Session::run() (catch.hpp:9549)
==1352==    by 0x267BCE: Catch::Session::run(int, char**) (catch.hpp:9517)
==1352== 
==1352== 512 bytes in 1 blocks are indirectly lost in loss record 9 of 12
==1352==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==1352==    by 0x2F9FA9: __gnu_cxx::new_allocator<ndsl::net::TcpConnection::SInfo*>::allocate(unsigned long, void const*) (new_allocator.h:104)
==1352==    by 0x2F9D34: std::allocator_traits<std::allocator<ndsl::net::TcpConnection::SInfo*> >::allocate(std::allocator<ndsl::net::TcpConnection::SInfo*>&, unsigned long) (alloc_traits.h:436)
==1352==    by 0x2F9925: std::_Deque_base<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::_M_allocate_node() (stl_deque.h:600)
==1352==    by 0x2F96C5: std::_Deque_base<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::_M_create_nodes(ndsl::net::TcpConnection::SInfo***, ndsl::net::TcpConnection::SInfo***) (stl_deque.h:725)
==1352==    by 0x2F9271: std::_Deque_base<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::_M_initialize_map(unsigned long) (stl_deque.h:699)
==1352==    by 0x2F8E98: std::_Deque_base<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::_Deque_base() (stl_deque.h:490)
==1352==    by 0x2F8D2B: std::deque<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::deque() (stl_deque.h:884)
==1352==    by 0x2F82DD: ndsl::net::TcpConnection::TcpConnection() (TcpConnection.cc:28)
==1352==    by 0x2F411D: ____C_A_T_C_H____T_E_S_T____0() (TcpConnectionTest.cc:70)
==1352==    by 0x26B0B5: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1352==    by 0x26A818: Catch::TestCase::invoke() const (catch.hpp:10232)
==1352== 
==1352== 512 bytes in 1 blocks are indirectly lost in loss record 10 of 12
==1352==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==1352==    by 0x2F9FA9: __gnu_cxx::new_allocator<ndsl::net::TcpConnection::SInfo*>::allocate(unsigned long, void const*) (new_allocator.h:104)
==1352==    by 0x2F9D34: std::allocator_traits<std::allocator<ndsl::net::TcpConnection::SInfo*> >::allocate(std::allocator<ndsl::net::TcpConnection::SInfo*>&, unsigned long) (alloc_traits.h:436)
==1352==    by 0x2F9925: std::_Deque_base<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::_M_allocate_node() (stl_deque.h:600)
==1352==    by 0x2F96C5: std::_Deque_base<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::_M_create_nodes(ndsl::net::TcpConnection::SInfo***, ndsl::net::TcpConnection::SInfo***) (stl_deque.h:725)
==1352==    by 0x2F9271: std::_Deque_base<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::_M_initialize_map(unsigned long) (stl_deque.h:699)
==1352==    by 0x2F8E98: std::_Deque_base<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::_Deque_base() (stl_deque.h:490)
==1352==    by 0x2F8D2B: std::deque<ndsl::net::TcpConnection::SInfo*, std::allocator<ndsl::net::TcpConnection::SInfo*> >::deque() (stl_deque.h:884)
==1352==    by 0x2F82DD: ndsl::net::TcpConnection::TcpConnection() (TcpConnection.cc:28)
==1352==    by 0x2FB0CF: ndsl::net::TcpClient::onConnect(ndsl::net::EventLoop*, bool, ndsl::net::SocketAddress4*) (TcpClient.cc:52)
==1352==    by 0x2F4246: ____C_A_T_C_H____T_E_S_T____0() (TcpConnectionTest.cc:78)
==1352==    by 0x26B0B5: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1352== 
==1352== 832 (16 direct, 816 indirect) bytes in 1 blocks are definitely lost in loss record 11 of 12
==1352==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==1352==    by 0x2F417B: ____C_A_T_C_H____T_E_S_T____0() (TcpConnectionTest.cc:77)
==1352==    by 0x26B0B5: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1352==    by 0x26A818: Catch::TestCase::invoke() const (catch.hpp:10232)
==1352==    by 0x2658F0: Catch::RunContext::invokeActiveTestCase() (catch.hpp:9104)
==1352==    by 0x26564A: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:9078)
==1352==    by 0x26434C: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:8861)
==1352==    by 0x266C12: Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) (catch.hpp:9394)
==1352==    by 0x267E59: Catch::Session::runInternal() (catch.hpp:9592)
==1352==    by 0x267C2E: Catch::Session::run() (catch.hpp:9549)
==1352==    by 0x267BCE: Catch::Session::run(int, char**) (catch.hpp:9517)
==1352==    by 0x27AF84: main (test.cc:16)
==1352== 
==1352== 976 (88 direct, 888 indirect) bytes in 1 blocks are definitely lost in loss record 12 of 12
==1352==    at 0x4C2C21F: operator new(unsigned long) (vg_replace_malloc.c:334)
==1352==    by 0x2F409A: ____C_A_T_C_H____T_E_S_T____0() (TcpConnectionTest.cc:60)
==1352==    by 0x26B0B5: Catch::TestInvokerAsFunction::invoke() const (catch.hpp:10331)
==1352==    by 0x26A818: Catch::TestCase::invoke() const (catch.hpp:10232)
==1352==    by 0x2658F0: Catch::RunContext::invokeActiveTestCase() (catch.hpp:9104)
==1352==    by 0x26564A: Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (catch.hpp:9078)
==1352==    by 0x26434C: Catch::RunContext::runTest(Catch::TestCase const&) (catch.hpp:8861)
==1352==    by 0x266C12: Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) (catch.hpp:9394)
==1352==    by 0x267E59: Catch::Session::runInternal() (catch.hpp:9592)
==1352==    by 0x267C2E: Catch::Session::run() (catch.hpp:9549)
==1352==    by 0x267BCE: Catch::Session::run(int, char**) (catch.hpp:9517)
==1352==    by 0x27AF84: main (test.cc:16)
==1352== 
==1352== LEAK SUMMARY:
==1352==    definitely lost: 116 bytes in 3 blocks
==1352==    indirectly lost: 1,704 bytes in 9 blocks
==1352==      possibly lost: 0 bytes in 0 blocks
==1352==    still reachable: 0 bytes in 0 blocks
==1352==         suppressed: 0 bytes in 0 blocks
==1352== 
==1352== For counts of detected and suppressed errors, rerun with: -v
==1352== ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)
